import { CompendiumItem } from './compendiumTypes';

export const INITIAL_COMPENDIUM_ITEMS: CompendiumItem[] = [
  // 1. Characters
  {
    id: 'char_maren_vance',
    category: 'characters',
    title: 'Maren Vance',
    subtitle: 'Spellblade Prodigy · Aethelgard',
    description: 'Wielder of the Astral Edge and former archivist of the Grand Spire.',
    tags: ['Protagonist', 'Spellblade', 'Aethelgard', 'Fantasy'],
    worldOrigin: 'Aethelgard: The Shattered Realm',
    classification: 'Player Persona',
    rarityOrThreat: 'Heroic Tier',
    aspectRatio: '3:4',
    traits: ['Silver-streaked dark hair', 'Runic gauntlet on left forearm', 'Observant amber eyes', 'Midnight leather coat'],
    equipment: 'Astral Edge (Moon-silver broadsword), Archivist Signet',
    loreSnippet: 'Trained within the sealed vaults of the Grand Spire, Maren escaped before the fracturing of the Ley Conduit with only the Codex of Embers.',
    provenance: 'Created during Character Genesis',
    stats: { Level: 4, HP: 38, Mana: 45, 'Key Stat': 'INT / DEX' },
  },
  {
    id: 'char_nyx_kincaid',
    category: 'characters',
    title: 'Nyx Kincaid',
    subtitle: 'Neural Net Infiltrator · Neon Dominion',
    description: 'Freelance cipher breaker operating in the sub-levels of Neo-Veridia.',
    tags: ['Protagonist', 'Cyberpunk', 'Infiltrator', 'Neon Dominion'],
    worldOrigin: 'Neon Dominion: 2184',
    classification: 'Player Persona',
    rarityOrThreat: 'Veteran Tier',
    aspectRatio: '3:4',
    traits: ['Sub-dermal optical wiring', 'Matte black bomber jacket with cyan lining', 'Cybernetic right arm'],
    equipment: 'Onyx Deck Mk IV, Monomolecular Stiletto',
    loreSnippet: 'Once employed by the OmniCorp security bureau, Nyx went ghost after discovering the Genesis Subroutine.',
    provenance: 'Created during Genesis',
    stats: { Level: 3, Reflexes: 18, Logic: 16, Chrome: '42%' },
  },

  // 2. Equipment
  {
    id: 'eq_astral_edge',
    category: 'equipment',
    title: 'The Astral Edge',
    subtitle: 'Relic Weapon · Attuned',
    description: 'Forged from fallen starlight and quenched in lunar water from the Celestial Pool.',
    tags: ['Weapon', 'Blade', 'Relic', 'Aethelgard'],
    worldOrigin: 'Aethelgard: The Shattered Realm',
    classification: 'Weapon (Longsword)',
    rarityOrThreat: 'Legendary Relic',
    aspectRatio: '1:1',
    traits: ['Luminescent blue edge', 'Constellation engravings along the fuller', 'Hilt wrapped in wyrm-leather'],
    loreSnippet: 'The blade hums with resonant frequencies whenever planar rifts or void entities are near.',
    provenance: 'Discovered in Chapter 2 (Sunken Sanctum)',
    stats: { Damage: '1d8+3 Slashing + 1d6 Force', Weight: '3 lbs', Properties: 'Finesse, Versatile' },
  },
  {
    id: 'eq_aegis_ward_cloak',
    category: 'equipment',
    title: 'Aegisweave Ward Cloak',
    subtitle: 'Protective Armor · Enchanted',
    description: 'Woven with threads of condensed kinetic dampeners and protective sigils.',
    tags: ['Armor', 'Cloak', 'Defensive', 'Aethelgard'],
    worldOrigin: 'Aethelgard: The Shattered Realm',
    classification: 'Armor (Accessory)',
    rarityOrThreat: 'Rare',
    aspectRatio: '1:1',
    traits: ['Deep obsidian weave with golden geometric trim', 'Deflects ranged projectiles'],
    loreSnippet: 'Crafted by the weavers of House Valen to protect heralds crossing hostile badlands.',
    provenance: 'Reward from Elder Bran',
    stats: { AC_Bonus: '+1 AC', Resistance: 'Force & Radiant', Weight: '2 lbs' },
  },

  // 3. Skills & Powers
  {
    id: 'pow_starlight_surge',
    category: 'powers',
    title: 'Starlight Surge',
    subtitle: 'Evocation / Astral Discipline',
    description: 'Channels concentrated celestial energy through the weapon into a cascading wave.',
    tags: ['Magic', 'Spell', 'Combat', 'Astral'],
    worldOrigin: 'Aethelgard: The Shattered Realm',
    classification: 'Active Spell (Level 2)',
    rarityOrThreat: 'Discipline Rank II',
    aspectRatio: '1:1',
    traits: ['Radiant burst', '15-foot cone', 'Blinding flash on critical strike'],
    loreSnippet: 'The cornerstone technique of the Vanguard of the Dawn.',
    provenance: 'Learned at Sanctum Gateway',
    stats: { CastTime: '1 Action', Range: 'Self (15ft cone)', Cost: '2 Mana / Spell Slot II' },
  },
  {
    id: 'pow_neural_overclock',
    category: 'powers',
    title: 'Neural Overclock',
    subtitle: 'Cyberware Ability · Reflex',
    description: 'Briefly accelerates synaptic transmission, perceiving the world at one-third speed.',
    tags: ['Cybernetic', 'Reflex', 'Active', 'Neon Dominion'],
    worldOrigin: 'Neon Dominion: 2184',
    classification: 'Augment Skill',
    rarityOrThreat: 'Military Spec',
    aspectRatio: '1:1',
    traits: ['Pupil dilation', 'Adrenaline surge', 'Heat buildup in cranial chassis'],
    loreSnippet: 'Originally developed for orbital drop-shock troopers.',
    provenance: 'Installed at Neo-Veridia Black Clinic',
    stats: { Duration: '2 Rounds', Cooldown: '3 Turns', Benefit: '+4 Initiative & Extra Reaction' },
  },

  // 4. Key NPCs
  {
    id: 'npc_archivist_selene',
    category: 'npcs',
    title: 'Archivist Selene',
    subtitle: 'Keeper of the Celestial Vault · Aethelgard',
    description: 'Scholar and guardian who preserved the ancient constellation codices.',
    tags: ['Ally', 'Scholar', 'Faction Leader', 'Aethelgard'],
    worldOrigin: 'Aethelgard: The Shattered Realm',
    classification: 'Key NPC / Quest Giver',
    rarityOrThreat: 'Faction Leader',
    aspectRatio: '3:4',
    traits: ['Starlight spectacles', 'Robes of celestial indigo', 'Calm demeanor'],
    loreSnippet: 'Selene refuses to take sides in the High Council schism, choosing to protect knowledge for all future generations.',
    provenance: 'Met in Grand Spire Archives',
    stats: { Affiliation: 'Order of the Astrolabe', Disposition: 'Friendly (75/100)' },
  },
  {
    id: 'npc_viktor_kane',
    category: 'npcs',
    title: 'Viktor Kane',
    subtitle: 'Syndicate Fixer · Neon Dominion',
    description: 'High-stakes broker operating out of the Cobalt Lounge in Upper Spire.',
    tags: ['Neutral', 'Broker', 'Merchant', 'Neon Dominion'],
    worldOrigin: 'Neon Dominion: 2184',
    classification: 'Key NPC / Broker',
    rarityOrThreat: 'Syndicate Master',
    aspectRatio: '3:4',
    traits: ['Synthetic golden voice modulator', 'Tailored obsidian suit', 'Smoke rings from neural vapes'],
    loreSnippet: 'Kane trades exclusively in verified memories and cryptographic identities.',
    provenance: 'Met in Cobalt Lounge',
    stats: { Affiliation: 'Kuroshio Syndicate', Disposition: 'Pragmatic Neutral (50/100)' },
  },

  // 5. Creatures
  {
    id: 'creature_void_stalker',
    category: 'creatures',
    title: 'Void Stalker',
    subtitle: 'Planar Entity · Aberration',
    description: 'Predatory phase-shifting hound born from fractures in the dimensional membrane.',
    tags: ['Aberration', 'Hostile', 'Planar', 'Aethelgard'],
    worldOrigin: 'Aethelgard: The Shattered Realm',
    classification: 'Bestiary Entry',
    rarityOrThreat: 'Threat Rating: Alpha (CR 5)',
    aspectRatio: '4:3',
    traits: ['Shadowy tendrils instead of fur', 'Multiple glowing violet eyes', 'Silent stalking'],
    loreSnippet: 'Attracted by unchecked arcane surges and dimensional tears.',
    provenance: 'Encountered at Abyssal Rift',
    stats: { HP: 68, AC: 15, Speed: '50 ft (Blink 20 ft)', Weakness: 'Radiant Fire' },
  },
  {
    id: 'creature_aether_drake',
    category: 'creatures',
    title: 'Aether Drake',
    subtitle: 'Majestic Sky Leviathan · Draconic',
    description: 'Winged crystalline dragon that feeds on solar winds and charged ley crystals.',
    tags: ['Draconic', 'Neutral', 'Celestial', 'Aethelgard'],
    worldOrigin: 'Aethelgard: The Shattered Realm',
    classification: 'Bestiary Entry',
    rarityOrThreat: 'Threat Rating: Ancient (CR 12)',
    aspectRatio: '4:3',
    traits: ['Translucent sapphire scales', 'Prismatic breath weapon', 'Wing span of 80 feet'],
    loreSnippet: 'Roams the cloud peaks above the Sunken Sanctum. Rarely attacks unless nests are disturbed.',
    provenance: 'Spotted above Starfall Ridge',
    stats: { HP: 195, AC: 18, Speed: 'Fly 80 ft', Breath: 'Prismatic Beam (45 ft line)' },
  },

  // 6. Worlds Archive
  {
    id: 'world_aethelgard',
    category: 'worlds',
    title: 'Aethelgard: The Shattered Realm',
    subtitle: 'High Fantasy · Full D&D Ruleset',
    description: 'A floating archipelago held together by ancient leystones following the Great Cataclysm.',
    tags: ['Fantasy', 'Living World', 'D&D 5E', 'Archipelago'],
    worldOrigin: 'Curated Canonical Canon',
    classification: 'World Template',
    rarityOrThreat: 'Canon Tier 1',
    aspectRatio: '16:9',
    traits: ['Floating landmasses', 'Crystalline leylines', 'Ancient clockwork spires'],
    loreSnippet: 'A land where forgotten gods left behind living conduits of raw elemental power.',
    provenance: 'DreamBook Curated World',
    stats: { Eras: 3, Regions: 12, Factions: 4, CanonLevel: 'Official' },
  },
  {
    id: 'world_neon_dominion',
    category: 'worlds',
    title: 'Neon Dominion: 2184',
    subtitle: 'Cyberpunk Noir · Story Light',
    description: 'A towering mega-city ruled by megacorporations and underground digital syndicates.',
    tags: ['Cyberpunk', 'Sci-Fi', 'Investigation', 'Urban'],
    worldOrigin: 'Curated Canonical Canon',
    classification: 'World Template',
    rarityOrThreat: 'Canon Tier 1',
    aspectRatio: '16:9',
    traits: ['Endless rain', 'Holographic skyways', 'Sub-level neon alleys'],
    loreSnippet: 'In 2184, physical identity is a commodity traded on the dark net.',
    provenance: 'DreamBook Curated World',
    stats: { Districts: 9, Megacorps: 5, TechLevel: 'Transhuman' },
  },

  // 7. Visual Collection
  {
    id: 'vis_celestial_sanctum_cover',
    category: 'visuals',
    title: 'Celestial Sanctum at Twilight',
    subtitle: 'Approved World Cover Artwork',
    description: 'Grand panoramic illustration of the central leystone spire overlooking the cloud sea.',
    tags: ['Environment', 'Artwork', 'Approved', 'Aethelgard'],
    worldOrigin: 'Aethelgard: The Shattered Realm',
    classification: 'Environment Master',
    rarityOrThreat: 'High Res Asset',
    aspectRatio: '16:9',
    traits: ['Twilight sky', 'Deep indigo and gold palette', 'Atmospheric volumetric lighting'],
    loreSnippet: 'Approved canonical key art for the Aethelgard campaign.',
    provenance: 'Synthesized via DreamBook Visual Engine',
    stats: { Resolution: '4K Ultra', ColorSpace: 'PBG DreamBook', Status: 'Approved' },
  },
];
