import type { AiTaskCategory, TaskId } from './aiOrchestrator';

export interface AiTaskContract {
	task: TaskId;
	category: AiTaskCategory;
	requiredCapabilities: string[];
	preferredCapabilities: string[];
	requiredInputTypes: string[];
	requiredOutputTypes: string[];
	requiresStructuredOutput: boolean;
	preferredPools: string[];
	defaultTimeoutMs: number;
	defaultMaxTokens: number;
}

const CONTRACTS: Record<TaskId, AiTaskContract> = {
	'narrative.generate': {
		task: 'narrative.generate',
		category: 'narration',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['creative_writing', 'fast'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['text', 'json'],
		requiresStructuredOutput: false,
		preferredPools: ['creative', 'fast'],
		defaultTimeoutMs: 15000,
		defaultMaxTokens: 1800,
	},
	'character.dialogue': {
		task: 'character.dialogue',
		category: 'narration',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['creative_writing'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['text', 'json'],
		requiresStructuredOutput: false,
		preferredPools: ['fast', 'creative'],
		defaultTimeoutMs: 10000,
		defaultMaxTokens: 900,
	},
	'character.extract': {
		task: 'character.extract',
		category: 'character_genesis',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['fast', 'structured_extraction', 'structured_output'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['fast', 'reasoning'],
		defaultTimeoutMs: 20000,
		defaultMaxTokens: 2400,
	},
	'memory.extract': {
		task: 'memory.extract',
		category: 'character_genesis',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['fast', 'structured_extraction', 'structured_output'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['fast', 'long_context'],
		defaultTimeoutMs: 10000,
		defaultMaxTokens: 900,
	},
	'character.capability.propose': {
		task: 'character.capability.propose',
		category: 'capability_synthesis',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['reasoning', 'extended_thinking', 'structured_output'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['reasoning', 'creative'],
		defaultTimeoutMs: 16000,
		defaultMaxTokens: 1800,
	},
	'story.advice': {
		task: 'story.advice',
		category: 'gameplay_advice',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['fast'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['fast'],
		defaultTimeoutMs: 3500,
		defaultMaxTokens: 700,
	},
	'rules.adjudicate': {
		task: 'rules.adjudicate',
		category: 'rules',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['reasoning', 'extended_thinking', 'structured_output'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['reasoning'],
		defaultTimeoutMs: 10000,
		defaultMaxTokens: 1200,
	},
	'rules.analyze': {
		task: 'rules.analyze',
		category: 'rule_analysis',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['reasoning', 'extended_thinking', 'structured_output'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['reasoning', 'review'],
		defaultTimeoutMs: 10000,
		defaultMaxTokens: 1200,
	},
	'summary.scene': {
		task: 'summary.scene',
		category: 'summarization',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['fast', 'long_context'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['text', 'json'],
		requiresStructuredOutput: false,
		preferredPools: ['fast', 'long_context'],
		defaultTimeoutMs: 8000,
		defaultMaxTokens: 900,
	},
	'world.generate': {
		task: 'world.generate',
		category: 'world_generation',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['creative_writing', 'reasoning'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['creative', 'reasoning'],
		defaultTimeoutMs: 20000,
		defaultMaxTokens: 3000,
	},

	'speech.generate': {
		task: 'speech.generate',
		category: 'speech',
		requiredCapabilities: ['speech_synthesis'],
		preferredCapabilities: ['tts'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['audio'],
		requiresStructuredOutput: false,
		preferredPools: ['speech'],
		defaultTimeoutMs: 15000,
		defaultMaxTokens: 1200,
	},
	'speech.transcribe': {
		task: 'speech.transcribe',
		category: 'speech',
		requiredCapabilities: ['speech_transcription'],
		preferredCapabilities: ['stt'],
		requiredInputTypes: ['audio'],
		requiredOutputTypes: ['text', 'json'],
		requiresStructuredOutput: false,
		preferredPools: ['transcription'],
		defaultTimeoutMs: 15000,
		defaultMaxTokens: 1000,
	},
	'combat.tactics': {
		task: 'combat.tactics',
		category: 'tactical_reasoning',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['reasoning', 'extended_thinking', 'structured_output'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['reasoning'],
		defaultTimeoutMs: 7000,
		defaultMaxTokens: 1400,
	},
	'tactical.reason': {
		task: 'tactical.reason',
		category: 'tactical_reasoning',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['reasoning', 'extended_thinking', 'structured_output'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['reasoning'],
		defaultTimeoutMs: 7500,
		defaultMaxTokens: 1500,
	},
	'combat.animation.plan': {
		task: 'combat.animation.plan',
		category: 'tactical_reasoning',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['fast'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['fast'],
		defaultTimeoutMs: 7000,
		defaultMaxTokens: 900,
	},
	'capability.explain': {
		task: 'capability.explain',
		category: 'capability_explanation',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['fast', 'creative_writing'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['text', 'json'],
		requiresStructuredOutput: false,
		preferredPools: ['fast', 'creative'],
		defaultTimeoutMs: 5000,
		defaultMaxTokens: 800,
	},
	'intent.interpret': {
		task: 'intent.interpret',
		category: 'intent_interpretation',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['fast', 'structured_extraction', 'structured_output'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['fast'],
		defaultTimeoutMs: 5000,
		defaultMaxTokens: 800,
	},
	'capability.synthesize': {
		task: 'capability.synthesize',
		category: 'capability_synthesis',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['reasoning', 'extended_thinking', 'structured_output'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['reasoning', 'creative'],
		defaultTimeoutMs: 16000,
		defaultMaxTokens: 2200,
	},
	'research.query': {
		task: 'research.query',
		category: 'research',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['reasoning', 'long_context', 'tools'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['long_context', 'reasoning', 'creative'],
		defaultTimeoutMs: 15000,
		defaultMaxTokens: 1800,
	},
	'research.world-brief': {
		task: 'research.world-brief',
		category: 'research',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['reasoning', 'long_context'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['json'],
		requiresStructuredOutput: true,
		preferredPools: ['long_context', 'reasoning'],
		defaultTimeoutMs: 15000,
		defaultMaxTokens: 2000,
	},
	'narrative.review': {
		task: 'narrative.review',
		category: 'narration',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['reasoning', 'creative_writing'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['text', 'json'],
		requiresStructuredOutput: false,
		preferredPools: ['review', 'reasoning'],
		defaultTimeoutMs: 8000,
		defaultMaxTokens: 1200,
	},
	'utility.inspect': {
		task: 'utility.inspect',
		category: 'research',
		requiredCapabilities: ['text_generation'],
		preferredCapabilities: ['fast'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['text', 'json'],
		requiresStructuredOutput: false,
		preferredPools: ['fast', 'utility'],
		defaultTimeoutMs: 6000,
		defaultMaxTokens: 800,
	},
	'image.generate': {
		task: 'image.generate',
		category: 'image',
		requiredCapabilities: ['image_generation'],
		preferredCapabilities: ['image_generation'],
		requiredInputTypes: ['text'],
		requiredOutputTypes: ['image'],
		requiresStructuredOutput: false,
		preferredPools: ['creative'],
		defaultTimeoutMs: 30000,
		defaultMaxTokens: 1200,
	},
};

export function getAiTaskContract(task: TaskId): AiTaskContract {
	return CONTRACTS[task];
}

export function getAllAiTaskContracts(): AiTaskContract[] {
	return Object.values(CONTRACTS);
}
