import { worldRepository } from '../repositories/worldRepository';
import { StoryThread, CanonicalGameplayEvent } from '../../src/types';

export class EmergentNarrativeEngine {
  public processCanonicalEvent(
    event: CanonicalGameplayEvent,
    repository = worldRepository
  ): { createdThread?: StoryThread; updatedThread?: StoryThread } {
    const existingThreads = repository.getStoryThreads(event.storyId);
    
    // Check if an existing thread is relevant
    const matchingThread = existingThreads.find((t) => t.status !== 'RESOLVED' && (t.locationId === event.locationId || t.title.toLowerCase().includes(event.eventType.toLowerCase())));

    if (matchingThread) {
      // Advance stage
      const newStage = Math.min(3, matchingThread.stage + 1);
      const updatedThread: StoryThread = {
        ...matchingThread,
        stage: newStage,
        status: newStage === 3 ? 'ESCALATED' : 'ACTIVE',
        updatedAt: new Date().toISOString(),
        evidenceGathered: [...(matchingThread.evidenceGathered || []), ...(event.evidenceItems || [])],
      };
      repository.saveStoryThread(updatedThread);
      return { updatedThread };
    } else {
      // Create new emergent thread
      const threadId = `thread_${Date.now()}_${Math.floor(Math.random() * 1000)}`;
      const createdThread: StoryThread = {
        threadId,
        storyId: event.storyId,
        title: `Emergent Thread: ${event.eventType.replace(/_/g, ' ')} at ${event.locationId || 'Unknown'}`,
        description: `Investigative thread generated by server resolution of event '${event.eventType}'`,
        category: 'EMERGENT_INVESTIGATION',
        status: 'ACTIVE',
        stage: 1,
        locationId: event.locationId || 'loc_unknown',
        evidenceGathered: event.evidenceItems || [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      repository.saveStoryThread(createdThread);
      return { createdThread };
    }
  }
}

export const emergentNarrativeEngine = new EmergentNarrativeEngine();
